# list an arbitrary set of topics to  subscribe to and stream:

# the more conservative between the two, stream_time and ram_limit are always in place
# the more conservative will be enforced
stream_time: 10  # seconds
# ram_limit: 0.25 # gb soft limit not hard enforced 
topics: ["/odom", 
         "/absodom", 
         "/stereo/left/camera_info",
         "/stereo/left/image_raw", 
         "/stereo/right/camera_info",
         "/stereo/right/image_raw", 
         "/velodyne_points",
         "/ooka"]

# comment out if default home/user/online_bagger is desired
# bag_package_path: ''

