# list an arbitrary set of topics to  subscribe to and stream:

      # down_stream_rate: 10 Hz 
ram_limit: 3.0 # gb 
topics: ["/odom", 
         "/absodom", 
         "/stereo/left/camera_info",
         "/stereo/left/image_raw", 
         "/stereo/right/camera_info",
         "/stereo/right/image_raw", 
         "/velodyne_points"]

bag_package_path: 'mil_ros_tools'

# leave bag name empty if default
bag_name: ''
