# list an arbitrary set of topics to  subscribe to and stream:
  # ram_limit is not yet implemented

stream_time: 30 # seconds
      # down_stream_rate: 10 Hz 
ram_limit: 3 # gb 
message_topics: ["/odom", 
                 "/absodom", 
                 "/stereo/left/camera_info",
                 "/stereo/left/image_raw", 
                 "/stereo/right/camera_info",
                 "/stereo/right/image_raw", 
                 "/velodyne_points"]
